name: apple_fotos_xmp_fixup
version: 0.1.0
publish_to: none

platforms:
  linux:
  macos:

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.12.0
  path: ^1.9.0
  xml: ^6.5.0
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0
  test: ^1.25.2
  xml_serializable: ^2.5.0

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/apple_fotos_xmp_fixup/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/apple_fotos_xmp_fixup/compare/v%from%...v%to%
