name: apple_fotos_xmp_fixup
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dev_dependencies:
  custom_lint: ^0.6.0
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.1
  test: ^1.25.2

dart_pre_commit:
  flutter-compat: false
