name: apple_fotos_xmp_fixup
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  exif: ^3.3.0
  meta: ^1.12.0
  xml: ^6.5.0
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.1
  test: ^1.25.2
  xml_serializable: ^2.5.0

dart_pre_commit:
  flutter-compat: false
