name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      unitTestPaths: ""

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.ci.outputs.enabledPlatforms }}
      buildRunner: true
